spring.application.name=gerenciador-estagios
spring.datasource.url=jdbc:mysql://localhost:3306/gerenciador_estagios
spring.datasource.username=root
spring.datasource.password=Andrew123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true